### ISSUE TITLE
Use webjar for the UI dependencies

### ISSUE THREAD

**Issue by danielpetisme** [vert-x3/vertx-starter#100]
Currently, the web app is using https://cdnjs.com/ to provide the 3rd party libs (like angukar.js, boostrap, etc.).
So you MUST have an (public) Internet connection to render properly the starter UI. This is not convenient for offline development, behind a corporate proxy or with some country limitations. 

Webjars are handy for java devs, they are declared as a classic dependency and bundle in the final jar.

I propose to use webjars wherever we can.

ATM, I don't know how to manager vertx asset dependencies
```
https://vertx.io/stylesheets/main.css
https://vertx.io/stylesheets/font-awesome.min.css
https://vertx.io/javascripts/styles/rainbow.min.css
https://vertx.io/assets/favicons/*
```

**Comment by danielpetisme** [comment]
In fact this one is harder than expected. When I look to https://www.webjars.org/ the css/js dependencies are not served by the same webjar provider (some time the version is not even proposed).

I don't feel very comfortable with mixing the provider (classic webjar vs npm webjar vs obsolete bower webjar).

Thoughts?

**Comment by tsegismont** [comment]
I'm not sure I understand, if your work offline then you can't communicate with the starter anyway.

As for corporate proxies, I was not aware cdnjs was blocked in some places - it serves a lot of websites after all :)

I don't think this is a blocker so if you can get a webjar config working, fine with me, otherwise let's stick to cdnjs for now.

**Comment by danielpetisme** [comment]
The angular.js is packaged with the Vert.x backend, so when offline the UI is just hitting localhost.

**Comment by tsegismont** [comment]
I see, you're talking about developing while being offline. Yes, that's an issue when using resources hosted on CDNs

**Comment by tsegismont** [comment]
No longer relevant, the frontend is built with vuejs + bootstrap now
