### ISSUE TITLE
Use the artifactId as root foolder for the archive

### ISSUE THREAD

**Issue by danielpetisme** [vert-x3/vertx-starter#102]
Currently, all the project files are located at the archive root

```
archive.zip/
  - src/
  - pom.xml
  - etc.
```
My proposal is to have 
```
archive.zip/
  - artifactId/
     - src/
     - pom.xml
      - etc.
```

The main benefits is to have a cleaner archive extraction, you don't have to create a folder before or remember the unzip `-d` option.

**Comment by tsegismont** [comment]
Fine with me
