### ISSUE TITLE
The new created project will not pause at any breakpoint when debugging

### ISSUE THREAD

**Issue by arniu** [vert-x3/vertx-starter#115]
### Context

When debug the new created gradle project in Intellij IDEA, breakpoints will not be trapped.

### Steps to reproduce

1. Create a new gradle project;
2. Open the project in Intellij IDEA, and add some breakpoints;
3. Open the gradle panel, select Tasks -> application -> `run`, and then right click "Debug ...";
4. And the program will not pause at any breakpoints.

### Extra

While debug the `runShadow` task, it works.

**Comment by arniu** [comment]
Duplicate issue: [#3159](https://github.com/eclipse-vertx/vert.x/issues/3159)

**Comment by arniu** [comment]
@tsegismont ?

**Comment by tsegismont** [comment]
In your IDE, create a remote debug configuration.

In the build file, add `'--java-opts="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"'` to run args:

```groovy
run {
  args = ['run', mainVerticleName, '--java-opts="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"', "--redeploy=$watchForChange", "--launcher-class=$mainClassName", "--on-redeploy=$doOnChange"]
}
```

Now the app won't start until you attach the remote debugger

**Comment by arniu** [comment]
Thanks very much!

**Comment by arniu** [comment]
According the [Vert.x Core Manual](https://vertx.io/docs/vertx-core/java/#_the_vertx_command_line):

> `java-opts` : the Java Virtual Machine options, uses the `JAVA_OPTS` environment variable if not set.

We can also do this for gradle projects:

```gradle
run {
  doFirst {
    environment.computeIfAbsent('JAVA_OPTS', {
      '-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005'
    })
  }
}
```
