### ISSUE TITLE
Generate Project downloading a text file and not a .zip project

### ISSUE THREAD

**Issue by ZinfinityDarshan** [vert-x3/vertx-starter#117]
### Context

The project is not getting generated as .zip file but a text file.

### Steps to reproduce

1. fill up required information on start.vertx.io to generate project zip
2. it downloads a .txt file

### Extra

![image](https://user-images.githubusercontent.com/44725488/70858905-b1cb3f80-1f30-11ea-9a2f-a65d2ca469e6.png)

**Comment by tsegismont** [comment]
Can you update the description to elaborate on the issue you have?

**Comment by ZinfinityDarshan** [comment]
Can you please look into this issue, we are in process to migrate our back-end from Spring java to Vertx for better performance, But unable to generate the project with required dependencies

**Comment by danielpetisme** [comment]
Hello,

1- Could you send a screenshot with the form filled in (just before you
click on the generate button).
2- Did you tried to create the project from a CLI? On the right part of the
generate button you will find a terminal icon. Click on it and you will
find either the curl and HTTPie commands if you are on Linux/Mac or
PowerShell if windows. Please try and give us the command too.
3- Which browser do you use?

Thanks

Le dim. 15 déc. 2019 à 07:19, ZinfinityDarshan <notifications@github.com> a
écrit :

**Comment by ZinfinityDarshan** [comment]
Hi,

Image of the form - 
![image](https://user-images.githubusercontent.com/44725488/70865932-ed91f380-1f88-11ea-8216-377c8e919d9d.png)

I tried CLI option but no .zip file got downloaded.

I am using chrome browser

Thanks

**Comment by danielpetisme** [comment]
Can you share the CLI command please.

You say no zip file has been downloaded, do you have any error message?

Are you using any (corporate) proxy?

Le dim. 15 déc. 2019 à 17:50, ZinfinityDarshan <notifications@github.com> a
écrit :

**Comment by tsegismont** [comment]
@ZinfinityDarshan I just tried on Chrome it works fine for me. I'm not sure why your download is named `caoching.txt`. Please rename it to `app.zip` to see if you can open the archive.

In case it's still doesn't work:

- try with another browser, or
- click on the right arrow sign to generate a CLI command, or
- use this GH template project https://github.com/vert-x3/vertx-maven-starter
