### ISSUE TITLE
Default JDK selection to latest OpenJDK

### ISSUE THREAD

**Issue by slinkydeveloper** [vert-x3/vertx-starter#120]
#### Describe the feature

The actual default selection for the JDK is 1.8. Who starts a new project probably wants to start with the latest version of the JDK (unless particular situations), so I think we should default to the latest OpenJDK, so OpenJDK 13

#### Contribution

I can take care of it, just point me the chords i need to touch :smile:

**Comment by vietj** [comment]
I think we should default to latests LTS, not latest JDK

**Comment by slinkydeveloper** [comment]
What if we have the choice for: 1.8/LTS/Latest and we default to LTS?

**Comment by vietj** [comment]
LGTM if @tsegismont is fine

**Comment by tsegismont** [comment]
Fine with me
