### ISSUE TITLE
Add Vert.x 4.0.0-milestone5 's new 'kids on the block' to the starter: Json Schema, Web Validation 

### ISSUE THREAD

**Issue by dasm0012** [vert-x3/vertx-starter#126]
### Describe the feature

The blog post https://vertx.io/blog/eclipse-vert-x-4-milestone-5-released/ announced that Vertx 4.0.0-milestone5 introduces new 3 components. It would be ncice if those 3 new components are made avaialable in the starter.

Vert.x Json Schema:
  <dependency>
    <groupId>io.vertx</groupId>
    <artifactId>vertx-json-schema</artifactId>
    <version>4.0.0-milestone5</version>
  </dependency>

Vert.x Web Validation
  <dependency>
    <groupId>io.vertx</groupId>
    <artifactId>vertx-json-schema</artifactId>
    <version>4.0.0-milestone5</version>
  </dependency>

Vert.x Web OpenAPI
  <dependency>
    <groupId>io.vertx</groupId>
    <artifactId>vertx-web-openapi</artifactId>
    <version>4.0.0-milestone5</version>
  </dependency>

#### Use cases

Benefit: Make all vertx componenents avaialble in the starter 

#### Contribution

At first sight it seemed like a simple update to the file https://github.com/vert-x3/vertx-starter/blob/master/src/main/resources/starter.json - however it isn't clear to me on how to restrict the avaialability of the new components when a end user selects a Vertx version for which the components are currently not avaialble (e.g. 3.x.x). Hence I hope some other contributor who understands the starter-configuration better then I do :-) could make the change.

**Comment by tsegismont** [comment]
Thanks for reporting this @dasm0012 . I'll take care of it.
