### ISSUE TITLE
Failed to create project: 9a1c5eb4-f0a8-4a3d-9cfa-d5a1fa88e752. Please report an issue.

### ISSUE THREAD

**Issue by userzcSpring** [vert-x3/vertx-starter#132]
### Context

The starter failed to create my project with following settings...

or

The generated project fails to build...

...etc

### Steps to reproduce

1. ...
2. ...
3. ...
4. ...

### Extra

* Anything that can be relevant

**Comment by tsegismont** [comment]
Please reopen if issue persists and you can provide more details (follow the issue template).
