### ISSUE TITLE
ShadowScript defaults to wrong path

### ISSUE THREAD

**Issue by tobiasmuehl** [vert-x3/vertx-starter#133]
`build/scriptsShadow/starter` on line 67 contains

```
CLASSPATH=$APP_HOME/lib/starter-1.0.0-SNAPSHOT-fat.jar
```

but it should be lib**s**

**Comment by tsegismont** [comment]
Can you elaborate? I can't see which file you're referring to.

**Comment by tobiasmuehl** [comment]
Go to https://start.vertx.io/ and use the default value "starter" for the Artifact ID, the generated zip file will contain this file under the `build/scriptsShadow/starter` path

**Comment by tsegismont** [comment]
This script is not be used as-is. In `build/distributions` you should find `starter-shadow-1.0.0-SNAPSHOT.tar` and `starter-shadow-1.0.0-SNAPSHOT.zip`. They both contain the script file in `bin` directory and the shadow jar in `lib` directory.

See https://github.com/johnrengelman/shadow/issues/155
