### ISSUE TITLE
The starter failed on mark all dependencies

### ISSUE THREAD

**Issue by andrehenriques** [vert-x3/vertx-starter#134]
### Context

The starter failed to create my project with following settings

### Steps to reproduce

Just mark all dependencies,
Version 3.9.2
Maven
Java

**Comment by vietj** [comment]
can you show the error ?

**Comment by andrehenriques** [comment]
this is number of project 94ef6427-fd58-4fc3-8e63-dc7f06760404

![image](https://user-images.githubusercontent.com/793897/90332808-8b194900-df96-11ea-9d9e-27615a2e0593.png)

**Comment by tsegismont** [comment]
The project creation failed because you can't generate a project which depends on both Vert.x Unit and Vert.x JUnit5
