### ISSUE TITLE
generate starter not work on jdk 1.8

### ISSUE THREAD

**Issue by qiuyi116** [vert-x3/vertx-starter#169]
### Questions

Project generate by starter not woking for jdk 1.8 and maven 3+, for there is `<release>` tag in pom.xml that only work for jdk 9+, as [stackoverflow says](https://stackoverflow.com/questions/49105941/intellij-maven-project-fatal-error-compiling-invalid-flag-release). However, the [guide](https://vertx.io/get-started/) say it's work for jdk 1.8+. 

As I remove `<release>` tag and use old config in pom.xml or using jdk 11, the starter works.

### Version

vert.x  version 4.0.2

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 1.8.0_275, vendor: Oracle Corporation, runtime: /usr/local/Cellar/openjdk@8/1.8.0+275/libexec/openjdk.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"

### Context
~/L/starter > mvn clean package
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------------< com.yqiu:starter >--------------------------
[INFO] Building starter 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ starter ---
[INFO] Deleting /Users/yqiu/Learn/starter/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ starter ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/yqiu/Learn/starter/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ starter ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/yqiu/Learn/starter/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.656 s
[INFO] Finished at: 2021-02-09T12:22:38+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project starter: Fatal error compiling: invalid flag: --release -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by tsegismont** [comment]
By default, the starter generate Java 11 projects but if you click on "Advanced Options" you can chose the target JDK version.
