### ISSUE TITLE
Project is not building when JDK version not matched with system one

### ISSUE THREAD

**Issue by abritov** [vert-x3/vertx-starter#191]
### Version

I've tried 4.1.2 & 4.2.0 snapshot template versions.

### Context

I encountered an exception which looks suspicious while ...

### Do you have a reproducer?

https://github.com/abritov/start-vertx-jdk-issue

### Steps to reproduce

1. Generate a clean project at https://start.vertx.io using JDK 11 or higher
2. Set default JDK to 1.8 in your PATH
3. Run "./mvnw package"

`[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------< com.example:starter >-------------------------
[INFO] Building starter 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ starter ---
[INFO] Deleting  ***EDITED***
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ starter ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory ***EDITED***
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ starter ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to  ***EDITED***
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.908 s
[INFO] Finished at: 2021-08-02T12:33:34+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project starter: Fatal error compiling: invalid flag: --release -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

### Extra
macos 10.12.6 
java version "1.8.0_131"

**Comment by tsegismont** [comment]
@abritov this is not a bug. Starting from JDK 9, there's a `release` option which guarantees that, for the specified version:

1. source code uses language constructs available in this version
2. output class files version corresponds to this version
3. source code does not use APIs available in a later version

If on the starter you select a JDK version that is greater than 9, the generated project is configured so that the compiler is invoked with the `release` option.

This is why you get this error when you try to compile with JDK 8.

**Comment by abritov** [comment]
I think it would be better to work in any case. Moreover, error message isn't clear about the actual reason of the problem.

**Comment by tsegismont** [comment]
If you need a project that can be built by JDK8, browse to start.vertx.io, expand the _Advanced Options_ and select JDK8.
