### ISSUE TITLE
Create the generated project Github repository

### ISSUE THREAD

**Issue by danielpetisme** [vert-x3/vertx-starter#24]
When a project is generated, it could be valuable to create the according github repository.
It's a feature that the jhipster generateor propose
http://start.jhipster.tech/

**Comment by vietj** [comment]
looks cool

**Comment by tsegismont** [comment]
Closing.

It sounds cool but then users will ask for GitHub private repos, Gitlab, Gitbucket... etc. Most often after you opened the project in the IDE, sharing on GitHub is one click away.
