### ISSUE TITLE
Support generating a kotlin project with gradle groovy syntax

### ISSUE THREAD

**Issue by ablil** [vert-x3/vertx-starter#252]
#### Describe the feature

Simply support generating a project with kotlin as a programming language, but the gradle build script with groovy syntax instead of kotlin

#### Use cases

Should be a basic options

**Comment by tsegismont** [comment]
Would you like to contribute this?

**Comment by ablil** [comment]
Sorry for the delay, I've made a small PR to fis this issue, you can double check
