### ISSUE TITLE
Advanced section

### ISSUE THREAD

**Issue by danielpetisme** [vert-x3/vertx-starter#30]
Currently, the starter is a quite simple form. It would be nice to have an advanced section to finely configure the generation. I open this discussion to track what could be part of this advanced section.

Right now what I have in mind:
* archive format (zip, tgz)
* the exhustive list of Vert.x components sorted by sections
* package name
* Java version
* systemd scripts

It's an open discussion so feel free to comment.

**Comment by greyseal** [comment]
How about generating a sample reactive project if a user has selected Vert.x RxJava v1 or V2 only.

**Comment by danielpetisme** [comment]
Duplicate #22
