### ISSUE TITLE
Escape special chars when generating Java identifiers

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-starter#32]
Current if I set my `artifactId` to _foo-bar_ the generated Java package is invalid. We should escape all the non valid chars and replace them by either `.` or `_`

**Comment by rdruss** [comment]
Is there a reason to automatically transform the invalid artifactId or should there just be validation which lets the user know there are invalid characters and ask them to change it.

**Comment by danielpetisme** [comment]
@rdruss Indeed that's a good option.
@vietj WDYT between notifying an error to the users and transforming the user input.

**Comment by tsegismont** [comment]
Fixed in #75
