### ISSUE TITLE
Empty dependency-definiton in pom.xml

### ISSUE THREAD

**Issue by codepitbull** [vert-x3/vertx-starter#35]
### Version

* vert.x starter: The one currently deployed on the main-page (http://start.vertx.io/)

### Context

Generated project contains an empty dependecy-definition:

```
<dependency>
         <groupId>io.vertx</groupId>
         <artifactId></artifactId>
         <version>${vertx.version}</version>
</dependency>
```

All other dependencies are fine.

### Do you have a reproducer?
See the screenshots of the params I used:

* Entry on start.vertx.io
<img width="1252" alt="bildschirmfoto 2017-11-11 um 22 08 16" src="https://user-images.githubusercontent.com/1409931/32693540-f4638054-c72c-11e7-91b6-f85d53f6c606.png">

**Comment by danielpetisme** [comment]
Hi, thanks for spotting this issue. It comes from the dependency definition in the project.
https://github.com/vert-x3/vertx-starter/blob/master/dependencies.json#L262

We provide a name and a description but the artifactId is not defined right now (as you can see).
Feel free to add it and make a PR.

**Comment by rdruss** [comment]
@danielpetisme and @codepitbull, I think this issue can be closed now.
