### ISSUE TITLE
Vert.x projects details should be stored externally.

### ISSUE THREAD

**Issue by danielpetisme** [vert-x3/vertx-starter#4]
Currently, when you generate a project, the vert.x project list as dependencies (vertx-web, vertx-mqtt, etc.) are fetched from a static json file hosted int the source code of the vertx-starter project.

This file provides many details such as a description of the vert.x project or a `Beta` flag. 

My proposition is to host this file somewhere on the Internet (in the official web site??) and make it available to `vertx-starter`.

**Comment by vietj** [comment]
why not use GitHub so it could be PR-ed ?

**Comment by danielpetisme** [comment]
Indeed, why not. In a dedicated repo? 
Does it sound over-kill to base the [Vert.x Documentation](http://vertx.io/docs/) page in this  dependency/project file? 
It's was is done for the [Vert.x Community page](http://vertx.io/community/) with the file [contributor.js](https://github.com/vert-x3/vertx-web-site/blob/master/src/main/community/contributors.js)

**Comment by danielpetisme** [comment]
Fix via https://github.com/danielpetisme/vertx-project-generator
