### ISSUE TITLE
vertx-unit dependency is missing scope test for fat jar to work out of the box

### ISSUE THREAD

**Issue by vladimir-dejanovic** [vert-x3/vertx-starter#44]
### Version

* vert.x starter:

### Context

I encounter issue when I used starter on vertx website. 

When I generated project, and just built the code and try to start it I got error 

$ java -jar target/vsite-1.0.0-SNAPSHOT-fat.jar 
The command 'run' is not a valid command.
See 'java -jar target/vsite-1.0.0-SNAPSHOT-fat.jar --help'

### Do you have a reproducer?

* Link to github project/gist

### Steps to reproduce

1. Generate project for vertx 3.5.0, lang java, dependency web and mysql
2. Just run mvn clean package
3. Then try to start fat jar with $ java -jar target/vsite-1.0.0-SNAPSHOT-fat.jar 
4. Error will appear 

The command 'run' is not a valid command.
See 'java -jar target/vsite-1.0.0-SNAPSHOT-fat.jar --help'

### Extra

Once I edited the generated pom file and put vertx-unit dependency in scope test, all was fine.

Kind Regards

**Comment by whisper-bye** [comment]
+1
I just modified my build.gradle file.
```groovy
ext {
  vertxVersion = '3.5.0'
  mainVerticleName = 'io.vertx.starter.MainVerticle' // this
}
```
```groovy
mainClassName = 'io.vertx.core.Launcher'

shadowJar {
  classifier = 'fat'
  manifest { // and this
    attributes 'Main-Verticle': mainVerticleName
  }
  mergeServiceFiles {
    include 'META-INF/services/io.vertx.core.spi.VerticleFactory'
  }
}
```

**Comment by danielpetisme** [comment]
Sorry for this delayed answer.
January as been a rush.
I'll check that ASAP.
