### ISSUE TITLE
Broken code in master branch

### ISSUE THREAD

**Issue by spodin** [vert-x3/vertx-starter#46]
Code in `master` branch is broken due to merged refactoring commits, so currently I'm not able to execute `./build_and_run.sh` script.

Problems:

- [Missed curly brace](https://github.com/vert-x3/vertx-starter/blob/master/vertx-starter-web/src/main/java/io/vertx/starter/web/service/DependencyService.java#L48)
- Mess in [ProjectResource.java](https://github.com/vert-x3/vertx-starter/blob/master/vertx-starter-web/src/main/java/io/vertx/starter/web/rest/ProjectResource.java)

**Comment by danielpetisme** [comment]
Sorry for this delayed answer.
January as been a rush.
I'll check that ASAP.

**Comment by reistiago** [comment]
Was going to contribute and fix a few issues, but it's hard to do so with a broken master. 

Is there any ETA for fixing master?

**Comment by vietj** [comment]
can you contribute a fix ?

**Comment by reistiago** [comment]
Not what I wanted to fix but I’ll try to give it a spin next week.

Fixing ProjectResource will be tricky.

**Comment by vietj** [comment]
why ?

**Comment by reistiago** [comment]
Because of the lack of context that I have about what was trying to be
achieved with the refactor that lead to that :) I’ll have a look at
the history to see if I can understand what was meant to happen

**Comment by reistiago** [comment]
@vietj @danielpetisme 

Please have a look at the [PR](https://github.com/vert-x3/vertx-starter/pull/48).

I'm going to be away for a few days, so I might be kind of slow following up on comments.

**Comment by reistiago** [comment]
@vietj @danielpetisme this can be closed now.
