### ISSUE TITLE
add intelliJ config instructions to starter's readme

### ISSUE THREAD

**Issue by fuzzysoft** [vert-x3/vertx-starter#47]
### Version

* vert.x starter:

### Context

this will help intelliJ users get the starter app running in intelliJ:

IntelliJ, Run/Debug Configurations
Add New Configuration, type "Application"
Main Class:                    io.vertx.core.Launcher
Program arguments:     run com.example.demo.MainVerticle

**Comment by danielpetisme** [comment]
Sorry for this delayed answer.
January as been a rush.
I'll check that ASAP.

**Comment by tsegismont** [comment]
@fuzzysoft can you clarify, were you looking for IntellIiJ setup for the starter app itself, or a generated app?

**Comment by fuzzysoft** [comment]
got it going w/ maven in IJ

how about a sample app MVC style with controller/manager (service)/model/dao classes for those of us migrating from Spring?

i'd buy every book on vertx avail... if only there were some

**Comment by tsegismont** [comment]
> how about a sample app MVC style with controller/manager (service)/model/dao classes for those of us migrating from Spring?

This is a sensible question BUT :)

We would like to keep the starter app simple stupid. Building a full generator (jHipster style is another story).

That being said, we are building an howto website (see https://groups.google.com/d/msg/vertx-dev/7PLksRMPCII/qjyeG2TnAwAJ) and the idea is that you would create a skeleton from the starter and then copy/paste the bits you need from one or more howtos.

>i'd buy every book on vertx avail... if only there were some

Our own @jponge is writing one right now https://www.manning.com/books/vertx-in-action
Follow him on Twitter, there are discount codes going out from time to time :)
