### ISSUE TITLE
Fat jar not executable due to missing resource on AppendingTransformer

### ISSUE THREAD

**Issue by reistiago** [vert-x3/vertx-starter#49]
### Version

* Version deployed to http://start.vertx.io at the time this bug was created.

### Context

Generated maven project fat jar fails to run.

Executing something like 

```java -jar project-1.0.0-SNAPSHOT-fat.jar```

yields

```The command 'run' is not a valid command.```

### Do you have a reproducer?

* Create a new project (maven based) and execute it

### Extra

This is due to a missing resource for the transformer AppendingTransformer on the generated pom.

Adding ```<resource>META-INF/services/io.vertx.core.spi.launcher.CommandFactory</resource>``` to the generated pom, fixes the issue

Possibly related with https://github.com/vert-x3/vertx-starter/issues/44

**Comment by shivamsriva31093** [comment]
We also faced this issue all of a sudden. For other projects, it runs without adding that CommandFactory to the pom. I don't follow the reason. Can you guide? @reistiago

**Comment by reistiago** [comment]
@shivamsriva31093 I haven't been working with vertx for a while.

This particular issue was fixed with this [commit](https://github.com/vert-x3/vertx-starter/commit/a3b3d40fb650a2d6d70eb8087784059727f34b90). 

I would recommend you to open a new issue, detailing the steps to  reproduce the error you are facing.

Sorry that I can't really help you
