### ISSUE TITLE
Please upgrade maven wrapper to support maven 3.5.*

### ISSUE THREAD

**Issue by leechenhwa** [vert-x3/vertx-starter#54]
In Windows the wrapper try to find "%M2_HOME%\bin\mvn.bat", but for maven 3.5.* the command is "%M2_HOME%\bin\mvn.cmd" by now.

**Comment by danielpetisme** [comment]
The generator has been moved to https://github.com/danielpetisme/vertx-project-generator and upgraded to Maven 3.5

Will be deployed soon

**Comment by danielpetisme** [comment]
@leechenhwa The web site has been updated (with the Maven 3.5).
Could you test please.

**Comment by danielpetisme** [comment]
Fixed via #57
