### ISSUE TITLE
Projects generated with start.vertx.io can't be run right away

### ISSUE THREAD

**Issue by hectorlf** [vert-x3/vertx-starter#55]
* vert.x starter: 3.5.3? whatever version is being served from http://start.vertx.io/

The generated project cannot be run with gradlew run, it says it's not able to find or load the main method (can't copy-paste the error as it's in spanish, sorry). Trying to run the fat jar fails with the same message.

It's easily fixable with some googling, but well, it shouldn't fail in the first place.

Edit: Windows environment, Gradle 4.9

**Comment by chengbaobao630** [comment]
java.lang.ClassCastException: io.vertx.core.Launcher cannot be cast to io.vertx.core.Verticle

**Comment by danielpetisme** [comment]
I'm working on a refactoring #57 

I delegate the generation to a gradle project:
https://github.com/danielpetisme/vertx-project-generator

I build some tests to check the execution of the generated projects. You can check: https://travis-ci.org/danielpetisme/vertx-project-generator

**Comment by hectorlf** [comment]
Works fine now, thanks. Closing.
