### ISSUE TITLE
Not able to add more dependencies after adding one

### ISSUE THREAD

**Issue by greyseal** [vert-x3/vertx-starter#58]
### Version
Vertx version 3.5.3
* vert.x starter:

### Context

I encountered an exception which looks suspicious while adding more dependencies after adding one.

### Do you have a reproducer?
No
* Link to github project/gist

### Steps to reproduce
Browser used: Chrome

1. Open http://start.vertx.io/
2. Add Version, Language, Build, GroupId, ArtifactId
3. Add a dependency, say Vertx.x Web. 
4. Now, try to add another dependency.

Result -> not able to add more dependencies. Also, not able to remove the selected dependency. Name of the selected dependency is also not viewable.

<img width="1626" alt="screen shot 2018-08-21 at 4 30 25 pm" src="https://user-images.githubusercontent.com/24274193/44398104-4c478880-a560-11e8-892e-afdf023580b8.png">

### Extra

* Anything that can be relevant

**Comment by danielpetisme** [comment]
I was trying a deployment... 
I rollbacked, it work now
![image](https://user-images.githubusercontent.com/593564/44398247-83f40780-a543-11e8-8371-d044dee4316a.png)
Sorry for the issue

**Comment by greyseal** [comment]
Oh!  I just checked, looks fine now.
Thanks.
