### ISSUE TITLE
Can we add a helper main method to deploy the verticle

### ISSUE THREAD

**Issue by greyseal** [vert-x3/vertx-starter#59]
### Version
Vertx version: 3.5.3
* vert.x starter:

### Context
Can we include a helper main method in the MainVerticle to deploy the verticle and run the server? Something like:

```
  public static void main(String[] args) {
    final Vertx vertx = Vertx.vertx();
    vertx.deployVerticle(new MainVerticle(), handler -> {
      if (handler.succeeded()) {
        System.out.println("Verticle deployed with deployment id: " + handler.result());
      } else {
        handler.cause().printStackTrace();
      }
    });
  }
```

**Comment by danielpetisme** [comment]
This is a usual concern. 
The `public static void main` app is the more natural way to start a java app but in Vert.x context you should see Vert.x as a kind of runtime your're developing on top of, just as you can do with Node.JS,  JavaEE  or Spring.

You need to delegate to vertx the bootstrap of your application, `io.vertx.core.Launcher` acts as a "Main-Class" as explaining in [Executing a Vert.x application packaged as a fat jar
](https://vertx.io/docs/vertx-core/java/#_executing_a_vert_x_application_packaged_as_a_fat_jar)
if you generate you project with http://start.vert.io, then you can use the preconfigured command
`./mvnw compile exec:java` or `./gradlew run` to launch the application.

If you want to run your application from your IDE, you should delegate to maven or gradle the startup with the above commands.

You can also have a look to the [vertx-boot](https://github.com/jponge/vertx-boot) project which aims to ease the startup of Vert.x applications.

**Comment by greyseal** [comment]
Okay, make sense. I also follow the same process of delegating to ``` io.vertx.core.Launcher``` to bootstrap vertx applications.

**Comment by rondinif** [comment]
tested with success on `<vertx.version>3.9.4</vertx.version>`, by adding to the MainVerticle.java
``` java
  public static void main(String[] args) {
    Vertx.vertx().deployVerticle(MainVerticle.class.getName());
  }
```
work and makes integration with IDE tooling such as `vscode` debugger very easy.
