### ISSUE TITLE
empty module name 'io.vertx::3.5.4' in gradle

### ISSUE THREAD

**Issue by mehmoodz** [vert-x3/vertx-starter#60]
### Version

* vert.x starter:

### Context

I encountered an exception which looks suspicious while building 

Generated with empty module name 'io.vertx::3.5.4'
```
Could not determine the dependencies of task ':shadowJar'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Could not find io.vertx::3.5.4.
     Required by:
         project :
```
### Do you have a reproducer?

* Link to github project/gist

### Steps to reproduce

1. Download starter
2. ./gradlew build

### Extra

* Anything that can be relevant

**Comment by danielpetisme** [comment]
Thanks! It's a good catch.
I'll look at it in the coming days.

**Comment by tsegismont** [comment]
Can't reproduce. Please reopen with detailed steps if it still fails in master.
