### ISSUE TITLE
Please add default .gitignore and redeploy script for enhancing this great starter

### ISSUE THREAD

**Issue by Fujujia** [vert-x3/vertx-starter#62]
### Version

* vert.x starter:

### Context

The starter is great tool I like, and hope more features can be added like default .gitignore  and redeploy script like redeploy.sh  https://github.com/vert-x3/vertx-guide-for-java-devs/tree/master/step-1.  etc development help features.

### Extra

* Anything that can be relevant

**Comment by danielpetisme** [comment]
Hi @Fujujia.
Have you tested the starter recently? The `.gitignore` file is generated.

Can we close this issue?

<img width="583" alt="Capture d’écran 2019-03-12 à 22 15 51" src="https://user-images.githubusercontent.com/593564/54236718-8ab08f00-4514-11e9-8ded-7ee9e12d0980.png">

**Comment by tsegismont** [comment]
Closing (out of date).
