### ISSUE TITLE
Use Gradle Kotlin DSL

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-starter#73]
This is just for the starter build.

**Comment by tsegismont** [comment]
@jponge would you mind to contribute this? If you think it's a matter of minutes and have a few cycles before the end of the week, please set the milestone to 2.0.0. Thanks!

**Comment by jponge** [comment]
Sure!

**Comment by jponge** [comment]
Can’t do it this week, but I will look into it the next one. Or when I finish the book chapter 6 :-)

**Comment by tsegismont** [comment]
No problem. I'll release 2.0.0 early next week and we can move to Kotlin
DSL later.

**Comment by tsegismont** [comment]
Closed via #79
