### ISSUE TITLE
Link to howtos website

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-starter#81]
When the howtos website is ready, add a link under the form like "What to do next? Explore Eclipse Vert.x howtos"

**Comment by tsegismont** [comment]
Assigned this one to you @jponge

**Comment by jponge** [comment]
First I need to have a root website for the howtos :-)

**Comment by tsegismont** [comment]
I know, no rush. I just file ideas when implementation seem like a low
hanging fruit.
