### ISSUE TITLE
Provide in the UI a curl command with a copy button

### ISSUE THREAD

**Issue by dazraf** [vert-x3/vertx-starter#87]
Firstly, great work!
This ticket asks if we can have `<pre>` style element in the UI with a parameterised curl command. Next to it, there would be a button (with a suitable icon) to copy the contents of the element, so that it can be pasted into a suitable terminal that would initiate the download of the project. Thanks again, Fuzz.

**Comment by danielpetisme** [comment]
I love the idea but I'm concerned by the UI/UX impact.

Should we show the curl command updating in live with the user's inputs or just showing it when the `Generate` button has been clicked?
In the case where the command is displayed in live should it displayed in the main area or visible in the "Advanced Section" @tsegismont is introducing with #89 ?

**Comment by tsegismont** [comment]
> Should we show the curl command updating in live with the user's inputs or just showing it when the Generate button has been clicked?

The url can be computed any time. I would prefer to avoid generating a project if it's going to be generated again via the CLI.

>In the case where the command is displayed in live should it displayed in the main area or visible in the "Advanced Section" @tsegismont is introducing with #89 ?

Visible all the time. It doesn't have to be fully visible (think GH clon panel). What's important is we provide a switch between *NIX and Windows and a "Copy to clipboard" button

**Comment by danielpetisme** [comment]
I ❤️  the GH clone panel idea!


Side thought, would be cool to add the url of generation into the generated `README`, kind of 
> Project generated by `https://start.vertx.io/starter.zip?groupId=com.github`
But that's another topic.

**Comment by danielpetisme** [comment]
@dazraf please have a look to https://github.com/vert-x3/vertx-starter/pull/96#issuecomment-477799126
