### ISSUE TITLE
Add to lombok

### ISSUE THREAD

**Issue by erayerdem** [vert-x3/vertx-starter#88]

**Comment by tsegismont** [comment]
Not sure what you mean. Configuring lombok on generated projects?

In this case, I'm sorry but we can't do this. There are so many projects out there that some people like, others don't, we can't include a switch for each and every one of them.

**Comment by rdruss** [comment]
@tsegismont, do you think this would something for a Howto?  People could contribute one for their personal favorites.

**Comment by tsegismont** [comment]
I don't believe so. Lombok can be used in any Java project and I haven't
heard of anything specific to Vert.x ones.
