### ISSUE TITLE
GDPR: do not log info related to users

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-starter#92]
Avoid user specific info in logs and Mongo:

- `groupId`
- `artifactId`
- `packageName`

**Comment by danielpetisme** [comment]
The `*Id` are personal data ??? I mean yes, one can add is name... Sounds crazy...

**Comment by tsegismont** [comment]
You may infer which company uses it and IANAL so I prefer to be
conservative :)

**Comment by danielpetisme** [comment]
Don't want to add a "V" at the end of GAFAM? :trollface:
