### ISSUE TITLE
Select dependencies panel

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-starter#97]
The `dependencies` input field lets you pick the modules you want to include in your project with autocompletion.

This is very handy when you know what you're looking for.

It would be nice to a popup panel (link under dependencies label) with all the available modules and a small description.

**Comment by danielpetisme** [comment]
👍 what about completing the advanced section with the list of dependencies group by theme (web, data, devops, etc.)

**Comment by tsegismont** [comment]
@danielpetisme could be done like this as well. I guess some prototyping could help determine which one works better.

**Comment by renannprado** [comment]
For those who would like to see the dependencies before this feature is merged:

https://github.com/vert-x3/vertx-starter/blob/master/src/main/resources/dependencies.json

**Comment by tsegismont** [comment]
Closed in #112
